using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Dagligdagen
{
    /// <summary>
    /// Interaction logic for MainWindowWpf.xaml
    /// </summary>
    public partial class MainWindowWpf : Window, System.Windows.Markup.IComponentConnector
    {
        public MainWindowWpf()
        {
            InitializeComponent();
        }

        private void button_Click(object sender, RoutedEventArgs e)
        {

        }

        private void listBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {

        }

        private void listBox_SelectionChanged_1(object sender, SelectionChangedEventArgs e)
        {

        }

        //Because the files would not work, I had to copy it in
        /*        #region Autogenerated code

                private bool _contentLoaded;

                /// <summary>
                /// InitializeComponent
                /// </summary>
                [System.Diagnostics.DebuggerNonUserCodeAttribute()]
                [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
                public void InitializeComponent()
                {
                    if (_contentLoaded)
                    {
                        return;
                    }
                    _contentLoaded = true;
                    System.Uri resourceLocater = new System.Uri("/DailyLifeWpf;component/mainwindow.xaml", System.UriKind.Relative);

                #line 1 "..\..\MainWindow.xaml"
                System.Windows.Application.LoadComponent(this, resourceLocater);

                #line default
                #line hidden
                }

                [System.Diagnostics.DebuggerNonUserCodeAttribute()]
                [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
                [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
                [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
                [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
                [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
                void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target)
                {
                    this._contentLoaded = true;
                }
                #endregion
                */
    }
}

